#include "errors.h"
#include <string>

using namespace std;

// 389. Find The Difference - Easy - Hash Table/Bit Manipulation
// -------------------------------------------------------------
// You are given two strings s and t.
// String t is generated by random shuffling string s and then adding one more letter at a random position.
// Return the letter that was added to t.
// -------------------------------------------------------------
// Solve #1 | 07/25/20 | Time: 4:25 | Avg. Runtime: 4ms

char findTheDifference(string s, string t) { // O(N + M) time, O(1) space
        // Initialize
        int mask = 0;
        // Mask all elements of s
        for (char c : s)
            mask ^= c;
        // Mask all elements of t
        for (char c : t)
            mask ^= c;
        // All elements in s would've been unmasked, only the extra character remains
        return mask;
    }
